### ISSUE TITLE
the cursor color can't be amended

### ISSUE THREAD

**Issue by luckey-xusir** [pmatatias/input-quantity#38]
<img width="737" alt="image" src="https://github.com/pmatatias/input-quantity/assets/142738386/8bbb9ef6-32ef-4152-ba60-72c536a82958">

**Comment by luckey-xusir** [comment]
<img width="629" alt="image" src="https://github.com/pmatatias/input-quantity/assets/142738386/8396ee78-4c4d-4ce3-91d2-f2abeb721b06">

**Comment by luckey-xusir** [comment]
also, text color?

**Comment by pmatatias** [comment]
Hi  @luckey-xusir , thank you for raise the issue.

My bad, I'm forget to export the `QtyFormProps`, going to fix it now

**Comment by luckey-xusir** [comment]
thanks

**Comment by pmatatias** [comment]
New version has been uploade to pub.dev
the issue should be fix on v 2.0.4

thank you for mentioned  the issue @luckey-xusir
