### ISSUE TITLE
Update intl to latest version

### ISSUE THREAD

**Issue by Prashanthkumar1998** [pmatatias/input-quantity#52]
please update intl to the latest version

**Comment by pmatatias** [comment]
Hi @Prashanthkumar1998 ,
Can you elaborate more?

The package is not depends on `intl` . only use `flutter` without first or third party plugin.

https://github.com/pmatatias/input-quantity/blob/a8cf42e50fb60b1fab5566ed64921691d6285c86/pubspec.yaml#L17-L24

**Comment by Prashanthkumar1998** [comment]
for my project i am using intl  ^0.18.1 , when trying add this packages getting error " every version of quantity_input depends on intl ^0.17.0 and figeit_app depends on intl ^0.18.1, quantity_input is forbidden."
  forbidden.

**Comment by Prashanthkumar1998** [comment]
Sorry now i am able to install

**Comment by Prashanthkumar1998** [comment]
Hi one suggestion if possible please add field value  so that we can reset it

**Comment by pmatatias** [comment]
Thank you.


> Hi one suggestion if possible please add field value so that we can reset it

Ok, I will considering creating this feature.
