### ISSUE TITLE
Cannot enter negative decimals in the InputQty input field

### ISSUE THREAD

**Issue by tonypioneer** [pmatatias/input-quantity#64]
## Description

When using InputQty, I found that I cannot enter a decimal point (.) after typing a negative sign (-) in the input field. That means I cannot type a negative decimal. However, if I enter a positive decimal, everything works well.

I found this issue may be caused by a bug in the original code of the input quantity package (Path: ~/.pub-cache/hosted/pub.dev/input_quantity-2.4.0/lib/src/input_qty.dart). It is located in Line 484 of this file.

```
        inputFormatters: [
          FilteringTextInputFormatter.allow(RegExp(r'^\d*\.?\-?\d*'))
        ],
```

I found the regular expression (RegExp) is not completely correct, and it may cause problems with negative numbers and decimals. The regular expression should be modified to allow the negative sign (-) to appear in front of the number and allow the decimal point (.). The following is the modified regular expression:

```
        inputFormatters: [
          FilteringTextInputFormatter.allow(RegExp(r'^-?\d*\.?\d*'))
        ],
```

I put the negative sign (-) to appear in front of the number and allow the decimal point (.). After this adjustment, everything works well.

![image](https://github.com/user-attachments/assets/4f8a3dd7-fae6-4668-8540-9fed2b8edb1a)

**Comment by pmatatias** [comment]
I think I missed that part. I really appreciate you pointing out the issue and providing a workaround. I'll update the `regex` pattern today, but feel free to open a PR—I’ll be happy to review and merge it. @tonypioneer

**Comment by tonypioneer** [comment]
> I think I missed that part. I really appreciate you pointing out the issue and providing a workaround. I'll update the `regex` pattern today, but feel free to open a PR—I’ll be happy to review and merge it. @tonypioneer

Hi @pmatatias, thank you very much for your reply. Perhaps I don't have the permission to create a new branch in this repository. Could you please help me create a new branch and submit a PR? Thank you very much. The only place I would like to modify is in `input-quantity/lib/src/input_qty.dart` at line 484, where `FilteringTextInputFormatter.allow(RegExp(r'^\d*\.?\-?\d*'))` needs to be changed to `FilteringTextInputFormatter.allow(RegExp(r'^-?\d*\.?\d*'))`.

**Comment by pmatatias** [comment]
@tonypioneer  How about fork the repo and then you can submit the PR?

**Comment by tonypioneer** [comment]
> @tonypioneer How about fork the repo and then you can submit the PR?

That's a good idea. I'll try that. Thank you @pmatatias.

**Comment by pmatatias** [comment]
I just publish new version https://pub.dev/packages/input_quantity
Thank you for your effort @tonypioneer 🔥

**Comment by tonypioneer** [comment]
> I just publish new version https://pub.dev/packages/input_quantity
> 
> Thank you for your effort @tonypioneer 🔥  

Thank you very much for your quick reply and update as well @pmatatias 👍
